version: '3.8'

services:
  portfolio-os:
    build: .
    container_name: nikhil-portfolio-os
    restart: always
    ports:
      - "3096:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - web

networks:
  web:
    external: false
